Run GitHub Action Pipeline on self-hosted runner

diff --git a/.github/workflows/frontend-pipeline.yaml b/.github/workflows/frontend-pipeline.yaml
--- a/.github/workflows/frontend-pipeline.yaml
+++ b/.github/workflows/frontend-pipeline.yaml
@@ -50,13 +50,13 @@ jobs:
         run: |
           echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
-    #     # Verify Built Image
-    #   - name: Verify Built Image
-    #     run: |
-    #         docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)
+        # Verify Built Image
+      - name: Verify Built Image
+        run: |
+            docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)
      
-      - name: List Images Before Tagging
-        run: docker images
+    #   - name: List Images Before Tagging
+    #     run: docker images
            
       - name: Tag and Push Docker Image
         run: |
