Add docker image tagging strategy

diff --git a/.github/workflows/frontend-pipeline.yaml b/.github/workflows/frontend-pipeline.yaml
--- a/.github/workflows/frontend-pipeline.yaml
+++ b/.github/workflows/frontend-pipeline.yaml
@@ -86,7 +86,7 @@ jobs:
 
       - name: Verify Built Image
         run: |
-          docker images | grep ${{ env.SERVICE_NAME }}:11 || (echo "Image not found!" && exit 1)
+          docker images | grep ${{ env.SERVICE_NAME }}:latest || (echo "Image not found!" && exit 1)
 
       - name: Trivy Scan for Docker Image
         run: |
@@ -106,6 +106,10 @@ jobs:
         run: |
           echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
-      - name: Push Docker Image
+      - name: Tag and Push Docker Image
         run: |
-          docker push ${{ env.SERVICE_NAME }}:11
+          docker tag ${{ env.SERVICE_NAME }}:latest ${{ env.SERVICE_NAME }}:${{ github.run_number }}
+          docker images
+          sleep 20
+          docker push ${{ env.SERVICE_NAME }}:${{ github.run_number }}
+          
