Verify docker images by docker inspect command

diff --git a/.github/workflows/frontend-pipeline.yaml b/.github/workflows/frontend-pipeline.yaml
--- a/.github/workflows/frontend-pipeline.yaml
+++ b/.github/workflows/frontend-pipeline.yaml
@@ -23,18 +23,18 @@ jobs:
        # Build the Docker image
       - name: Build Docker Image
         run: |
-            docker build -t ${{ env.SERVICE_NAME }}:latest -f src/frontend/Dockerfile src/frontend
+            docker build -t ${{ env.SERVICE_NAME }}:${{ github.run_number }} -f src/frontend/Dockerfile src/frontend
             docker images  # Log the images on the runner
 
        # Verify Built Image
       - name: Verify Built Image
         run: |
-            docker inspect --type=image frontend:latest || (echo "Image not found!" && exit 1)
+            docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)
 
 
       - name: Trivy Scan for Docker Image
         run: |
-          trivy image --severity HIGH,CRITICAL --exit-code 1 --scanners vuln ${{ env.SERVICE_NAME }}:latest || true
+          trivy image --severity HIGH,CRITICAL --exit-code 1 --scanners vuln ${{ env.SERVICE_NAME }}:${{ github.run_number }} || true
 
   push-to-dockerhub:
     needs: build-and-scan
@@ -50,16 +50,17 @@ jobs:
         run: |
           echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
+        # Verify Built Image
+      - name: Verify Built Image
+        run: |
+            docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)
+     
       - name: List Images Before Tagging
         run: docker images
-        
-    #   - name: Verify Image Before Tagging
-    #     run: |
-    #         docker inspect --type=image frontend:latest || (echo "Image not found!" && exit 1)        
-
+           
       - name: Tag and Push Docker Image
         run: |
-          docker tag ${{ env.SERVICE_NAME }}:latest ${{ env.DOCKERHUB_IMAGE_TAG }}:${{ github.run_number }}
+          docker tag ${{ env.SERVICE_NAME }}:${{ github.run_number }} ${{ env.DOCKERHUB_IMAGE_TAG }}:${{ github.run_number }}
           docker images
           sleep 20
           docker push ${{ env.DOCKERHUB_IMAGE_TAG }}:${{ github.run_number }}
